apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  labels:
    consumer: gop-file-server
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/web"
