apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: development
  name: jekyll-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
