#Service 'jekyll' uses targetPort: '4000', namespace: 'development'
#Service 'jekyll' uses Port: '8080', namespace: 'development'
#Service 'jekyll' uses NodePort: '30097', namespace: 'development'
apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: jekyll-node-service
spec:
  type: NodePort
  selector:
    run: jekyll
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 4000
    nodePort: 30097
