apiVersion: v1
kind: Pod
metadata:
  namespace: development
  name: jekyll
  labels:
    name: jekyll
spec:
  initContainers:
  - name: copy-jekyll-site
    image: kodekloud/jekyll
    command: ["jekyll", "new", "/site"]
    volumeMounts:
    - mountPath: /site
      name: site

  containers:
  - name: jekyll
    image: kodekloud/jekyll-serve
    volumeMounts:
    - mountPath: /site
      name: site
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 4000

    volumes:
    - name: site
      persistentVolumeClaim:
        claimName: jekyll-site
