#'developer-role', should have all(*) permissions for services in development namespace
#'developer-role', should have all permissions(*) for persistentvolumeclaims in development namespace
#'developer-role', should have all(*) permissions for pods in development namespace

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: developer-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services", "persistentvolumeclaims"]
  verbs: ["*"]
